# Generated by Django 4.2.3 on 2023-08-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="R",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("loc", models.CharField(max_length=100)),
                ("rating", models.CharField(max_length=3)),
                ("itemname", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("isveg", models.CharField(max_length=10)),
                (
                    "itemimage",
                    models.ImageField(
                        default=None, null=True, upload_to="media/item_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
                ("repassword", models.CharField(max_length=20)),
            ],
        ),
    ]
